### ISSUE TITLE
Issue running promacct

### ISSUE THREAD

**Issue by UncannyD** [kumina/promacct#1]
After installing promacct successfully I try to run it using **./promacct -i wlp2s0**, that results in the error **promacct: src/pcap.cc:30: void Pcap::Activate(const string&, std::size_t, std::size_t): Assertion `false && "Failed to activate"' failed.**. Any tips on what might be causing this?

**Comment by EdSchouten** [comment]
Yes, that's a bit of sloppy programming on my side. This shouldn't crash with a failed assertion, but return a proper error message. It means the network device doesn't exist or you lack permissions to open the device (i.e., you're not root). Will fix!

**Comment by EdSchouten** [comment]
Fixed in 02c16f640530d2145ecff2f48392d975b9396b90. Thanks for reporting!

**Comment by UncannyD** [comment]
That fixed it, thank you very much.
