### ISSUE TITLE
Project maintenance status

### ISSUE THREAD

**Issue by FedeBev** [kumina/promacct#2]
I would just like to know if the project is maintained and if requests/problems are taken into consideration.

Thank you

**Comment by timstoop** [comment]
Hi @FedeBev, the project is semi-maintained, as in, we use it internally ourselves and will therefore spend some time on fixing problems. However, for things we do not experience on our own setups, I'm afraid we have to rely on PRs to get them fixed. Our devs are spending some time every week picking up open PRs and other issues.
